app:
  storage:
    location: uploadDir

server:
  port: 9000

spring:
  thymeleaf:
    prefix: classpath*:/templates/
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  http:
    multipart:
      enabled: false

  datasource:
    name: cartracker
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/carInformation/database/carInformation
    username: SA
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update  # validate or update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.HSQLDialect
        generate-ddl: no
        show_sql: false
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG