server:
  port: 9004

spring:
  messages:
    basename: admin.messages, shared.messages, customer.messages, lookup.messages,  supplyinventory.messages, sales.messages, consult.messages, vmas.messages
  datasource:
    url: jdbc:mysql://localhost:3306/salesconsult
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate-ddl: no
        show_sql: true
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

#    properties:
#      hibernate:
#        show_sql: false
#        use_sql_comments: false
#        format_sql: false
#        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.tool.schema: DEBUG