app:
  datasource:
    global:
      jdbc-url: jdbc:mysql://localhost:3306/new_vmas
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    tenant:
      jdbc-url: jdbc:mysql://localhost:3306/new_vmas
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  thymeleaf:
    cache: false  # TODO turn on for production

  messages:
    basename: admin.messages, shared.messages, customer.messages, lookup.messages,  supplyinventory.messages, sales.messages, consult.messages, vmas.messages
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    database: mysql
#    properties:
#      hibernate:
#        generate-ddl: no
#        show_sql: true
#        use_sql_comments: true
#        format_sql: true
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "springboot-ssl"
          keystore:
            location: "classpath:springboot-ssl.p12"
            password: "vmasvmas"
            type: "PKCS12"
  devtools:
    restart:
      additional-exclude:
        - "admin-module-*.jar"
        - "**/admin-module-*.jar"
        - "lib/admin-module-*.jar"
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.tool.schema: INFO

server:
  servlet:
    session:
      timeout: 15m
  #    context-path: /gwz-vmas

  http2:
    enabled: true
  port: 8443
  address: 0.0.0.0
  ssl:
    bundle: web-server
    client-auth: none